/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tf-ds-gym.glb --transform 
Files: tf-ds-gym.glb [1.14MB] > C:\Users\M. Alperen Efiloğlu\Desktop\three-fiber-demo\public\tf-ds-gym-transformed.glb [115.14KB] (90%)
Author: Binkley-Spacetrucker (https://sketchfab.com/Binkley-Piratepants)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tf-ds-gym-f3b26bfbb3174562a28bcf01f3b40f44
Title: TF-DS-GYM
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Gym(props) {
  const { nodes, materials } = useGLTF('/tf-ds-gym-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} position={[34856.859, 10786.32, -34431.078]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/tf-ds-gym-transformed.glb')
