/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 super_human.glb --transform 
Files: super_human.glb [34.56MB] > C:\Users\M. Alperen Efiloğlu\Desktop\three-fiber-demo\public\super_human-transformed.glb [1.33MB] (96%)
Author: Davyd Vidiger (https://sketchfab.com/cryunreal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/super-human-7aa58e978b9f4357b8e73d8e0440c896
Title: Super Human
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Human(props) {
  const { nodes, materials } = useGLTF('/super_human-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.blinn1SG} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.temp_ldefault1} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/super_human-transformed.glb')
